### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by TGTGamer** [NxtLvLSoftware/git-subtree-action#2]
Heya pal. 

First up: Amazing work, this is exactly what I was looking for to connect my `/docs` to my external `repo-wiki` (not the github built in one as I have another solution for that). So thank you for saving me a bit of time. 

Question uno: 
Dumb question probably, does this need to be the public or private SSH? Have you got links to documentation which might help or could you explain exactly what is required?

Question two: 
So I haven't yet run this, it's actually commented out of my workflow until I am sure about the above question, but could you explain how it will handle if the remote repo does not exist. I intend to use this in the organisation workflow, which most of them have a separate wiki, but some don't. 

Question three: 
Can we define which branch I want to push onto? Would be amazing to be able to push to specific branch, and if it doesn't exist, create that branch. Especially useful for Gitbook which allows for versioning

Look forward to your response. 
TGT

**Comment by JackNoordhuis** [comment]
1.) Public key. Readme has been updated to specify this.
2.) It will just create the branch if it does not exist.
3.) Yes, a new option was added in the latest release so use `@1.1`.

**Comment by medeirosinacio** [comment]
how to configure ssh key? I tried to put the public key registered in the destination repository but it didn't work
